name: Node.js Package

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      #2. Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          registry-url: ${{env.LOCAL_REGISTRY}}
          scope: "@mpaynesecurity"

      # 3. Run from the root so Bun installs public dependencies from npmjs.org
      - name: Install Monorepo Dependencies
        run: bun install --frozen-lockfile
        env:
          BUN_AUTH_TOKEN: ${{ env.GITHUB_TOKEN }}

      # 4. Bump versions
      - name: Bump Versions
        run: bun pm version patch --no-git-tag-version --force

      # 5. Publish to lcal registry
      - name: Publish Package
        run: bun publish
        working-directory: ./plugin
        env:
          BUN_AUTH_TOKEN: ${{ env.GITHUB_TOKEN }}